# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    tags: ["*"]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swiftc macocrpdf.swift -o macocrpdf
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "macocrpdf"
